spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nikhil
    username: Nikhil
    password: nikhil
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: Authentication
  config:
    import: "optional:configserver:http://localhost:8007/"



# Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: nikhilkorukoppula@gmail.com
    password: ufwbsbnwkdjobmlc
    properties:
     mail:
     smtp:
     auth: true
     starttls:
     enable: true
  servlet:
   multipart:
    enabled: true
    file-size-threshold: 2KB
    max-file-size: 200MB
    max-request-size: 215MB

