spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nikhil
    username: Nikhil
    password: nikhil
  jpa:
    hibernate:
      ddl-auto: update

      
server:
 port: 8085